name: Swift Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: fwal/setup-swift@v1
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true # Runs 'bundle install' and caches installed gems automatically
    - name: Generate Swift Code & Run Tests
      run: bundle exec rake test_swift
